### ISSUE TITLE
Save output to ansi text file

### ISSUE THREAD

**Issue by greenseeker** [TheZoraiz/ascii-image-converter#4]
Is there a way to save the output as an ansi text file? If I try to redirect output, it barfs during terminal size detection. If I also specify the output size with -d, it complains the terminal is too small.

Update: I was able to capture the output using `script` but it would certainly be nice to have a proper save-as-ansi option.

**Comment by TheZoraiz** [comment]
@greenseeker I'm taking a guess here, but I believe the error occurs because you're redirecting `stdout` to a file. The tool detects terminal size from `stdout` every time, which is usually the terminal, so I can see how that's an issue. Custom dimensions also won't work since they check whether the width exceeds the terminal (`stdout` again) as well.

I wanted to keep the flags simple for most users so I'm not sure about adding character encoding functionality, because then covering only ANSI characters set would seem inappropriate. For the time being, I believe you can change the saved text file encoding with tools like `iconv` or `recode`. 

Will have to think about this. Thanks for pointing out the issues though, I'm a bit busy these days but I'll try to make a fix soon.

**Comment by greenseeker** [comment]
I suspected the same regarding the crash/failure when redirecting output.

You're already encoding it in ansi to write to the screen; I was just looking for a nice way to save that to a file as well. If you were to do so, optimizing the escape codes would be nice also. At the moment, the color is being reset to defaults and then set to the new color in between every character, even if that character is the same color as the previous one.
